//GLSL version to use
#version 460

#extension GL_GOOGLE_include_directive : enable
#include "ShaderCommon.h"
#include "HelloTriangle.hpp"

// #extension GL_EXT_debug_printf : enable

layout(push_constant) uniform Constants {
	HelloTriangleConstants ctx;
};

#define image images[ctx.outputImageRID]

layout (local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE) in;


void main() 
{
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);

	if(texelCoord.x < size.x && texelCoord.y < size.y)
	{
		vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

		if(gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0)
		{
			color.x = float(texelCoord.x)/(size.x);
			color.y = float(texelCoord.y)/(size.y);	
		}
	
		imageStore(image, texelCoord, color);
		// debugPrintfEXT("Some float=%f, some int=%d", color.x, texelCoord.x); 
	}
}